"""Initial Migration

Revision ID: 102aeb9dc658
Revises:
Create Date: 2023-06-13 16:17:15.428512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102aeb9dc658'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=55), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

     if environment == "production":
        op.execute(f"ALTER TABLE categories SET SCHEMA {SCHEMA};")


    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('profile_pic', sa.String(length=2000), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )

     if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")



    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_is', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['following'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_is'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_is', 'following')
    )

     if environment == "production":
        op.execute(f"ALTER TABLE follows SET SCHEMA {SCHEMA};")




    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=55), nullable=False),
    sa.Column('owner_review', sa.String(length=500), nullable=False),
    sa.Column('owner_rating', sa.Integer(), nullable=False),
    sa.Column('watching_on', sa.String(length=55), nullable=True),
    sa.Column('post_img', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

     if environment == "production":
        op.execute(f"ALTER TABLE posts SET SCHEMA {SCHEMA};")



    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_body', sa.String(length=500), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


     if environment == "production":
        op.execute(f"ALTER TABLE reviews SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('posts')
    op.drop_table('follows')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
